### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by ngbusca** [adblockradio/adblockradio#5]
Trying to install adblockradio fails miserably. The error messages pasted below... any hints? 

``` 
> adblockradio@1.0.0 postinstall /Users/nicolas.busca/Documents/adblockradio
> install-app-deps

  • please use as subcommand: electron-builder install-app-deps
  • electron-builder version=20.38.2
  • rebuilding native production dependencies platform=darwin arch=x64
Error: /usr/local/bin/node exited with code 1
Output:

> sqlite3@4.0.4 install /Users/nicolas.busca/Documents/adblockradio/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3240000/sqlite3.c
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3240000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3240000/sqlite3.o
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3240000/sqlite3.o
  LIBTOOL-STATIC Release/sqlite3.a
  LIBTOOL-STATIC Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/nicolas.busca/Documents/adblockradio/node_modules/sqlite3/lib/binding/electron-v1.4-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/nicolas.busca/Documents/adblockradio/node_modules/sqlite3/lib/binding/electron-v1.4-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)

Error output:
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.4/electron-v1.4-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.4 and electron@1.4.13 (electron-v1.4 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.0.4 and electron@1.4.13 (electron-v1.4 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Connection closed while downloading tarball file
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from ../src/database.cc:4:
../src/database.h:6:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from ../src/database.cc:4:
../src/database.h:6:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
1 warning and 1 error generated.
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/nicolas.busca/Documents/adblockradio/node_modules/sqlite3/lib/binding/electron-v1.4-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/nicolas.busca/Documents/adblockradio/node_modules/sqlite3/lib/binding/electron-v1.4-darwin-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/nicolas.busca/Documents/adblockradio/node_modules/sqlite3
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/nicolas.busca/Documents/adblockradio/node_modules/sqlite3/lib/binding/electron-v1.4-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/nicolas.busca/Documents/adblockradio/node_modules/sqlite3/lib/binding/electron-v1.4-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/nicolas.busca/Documents/adblockradio/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/nicolas.busca/Documents/adblockradio/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/nicolas.busca/Documents/adblockradio/node_modules/sqlite3
node-pre-gyp ERR! node -v v10.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nicolas.busca/.npm/_logs/2019-01-25T15_11_35_831Z-debug.log
1 warning and 1 error generated.
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/nicolas.busca/Documents/adblockradio/node_modules/sqlite3/lib/binding/electron-v1.4-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/nicolas.busca/Documents/adblockradio/node_modules/sqlite3/lib/binding/electron-v1.4-darwin-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/nicolas.busca/Documents/adblockradio/node_modules/sqlite3
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

    at ChildProcess.childProcess.once.code (/Users/nicolas.busca/Documents/adblockradio/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:610:12)
From previous event:
    at _rebuild (/Users/nicolas.busca/Documents/adblockradio/node_modules/app-builder-lib/src/util/yarn.ts:179:5)
    at rebuild (/Users/nicolas.busca/Documents/adblockradio/node_modules/app-builder-lib/out/util/yarn.js:163:19)
    at /Users/nicolas.busca/Documents/adblockradio/node_modules/app-builder-lib/src/util/yarn.ts:20:11
From previous event:
    at _installOrRebuild (/Users/nicolas.busca/Documents/adblockradio/node_modules/app-builder-lib/out/util/yarn.js:71:28)
    at installOrRebuild (/Users/nicolas.busca/Documents/adblockradio/node_modules/app-builder-lib/out/util/yarn.js:55:28)
    at /Users/nicolas.busca/Documents/adblockradio/node_modules/electron-builder/src/cli/install-app-deps.ts:56:9
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at _installAppDeps (/Users/nicolas.busca/Documents/adblockradio/node_modules/electron-builder/out/cli/install-app-deps.js:176:26)
    at installAppDeps (/Users/nicolas.busca/Documents/adblockradio/node_modules/electron-builder/out/cli/install-app-deps.js:144:26)
    at main (/Users/nicolas.busca/Documents/adblockradio/node_modules/electron-builder/src/cli/install-app-deps.ts:65:10)
    at Object.<anonymous> (/Users/nicolas.busca/Documents/adblockradio/node_modules/electron-builder/src/cli/install-app-deps.ts:70:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adblockradio@1.0.0 postinstall: `install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the adblockradio@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nicolas.busca/.npm/_logs/2019-01-25T15_11_35_981Z-debug.log
```

**Comment by dest4** [comment]
Indeed this is a miserable fail! ^^

From the logs it looks you are on a UNIX platform. Linux? Mac?
I see three options:
1) Check you can build things in general on your platform:
`sudo apt-get install build-essential` or something like that.

2) Follow advice from the node-sqlite3 page and report back with what helped you
https://github.com/mapbox/node-sqlite3

3) Remove the "postinstall" line (and trailing comma the line above) in the `package.json` to skip the build specific to Electron. Then try to `npm install` again. But I doubt it will help you.

FYI I am working on making the installation simpler by removing the Python part.
Please report what helped you get through, so that I can make this easier for the other people.

**Comment by ngbusca** [comment]
> From the logs it looks you are on a UNIX platform. Linux? Mac?

That's right, I'm on a mac.

> 1. Check you can build things in general on your platform:

I can confirm that I can build things in general, so I moved to 2.

> 2. Follow advice from the node-sqlite3 page and report back with what helped you
>    https://github.com/mapbox/node-sqlite3

I wasn't sure what particular advice I should try from that page so I moved to 3.

> 3. Remove the "postinstall" line (and trailing comma the line above) in the `package.json` to skip the build specific to Electron. Then try to `npm install` again. But I doubt it will help you.
> 

That worked! The `node demo.js` seems to work as well. Thanks!

> FYI I am working on making the installation simpler by removing the Python part.
> Please report what helped you get through, so that I can make this easier for the other people.

**Comment by dest4** [comment]
Great news. I had put that postinstall line for Electron build in https://github.com/adblockradio/buffer but it causes more problems than what it solves. Personal TODO: remove that line.

**Comment by dest4** [comment]
I have removed the `postinstall` operation in https://github.com/adblockradio/adblockradio/commit/8b08867358e37666e6050463ceb1c66374e26469#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

A standard environment is now described in the Dockerfile https://github.com/adblockradio/adblockradio/blob/master/.circleci/images/primary/Dockerfile

Closing this now.
